### ISSUE TITLE
create contribute.md page 

### ISSUE THREAD

**Issue by codednepal** [codednepal/hacktober2022#21]

**Comment by SarbajitNeogi** [comment]
Hello @codednepal ,please assign this issue to me so that I can resolve this issue for hacktober fest 2022!!!!

**Comment by codednepal** [comment]
@SarbajitNeogi goog luck

**Comment by asmi-code** [comment]
assign me

**Comment by codednepal** [comment]
thankyou @SarbajitNeogi but we need seperate contribution md
